X =10
Y =2.5
NAME="Ananthsimha" 
IS_STUDENT=True

z= X + Y
print(z)
z= X - Y
print(z)
z= X * Y
print(z)
z= X / Y
print(z)
z= X // Y
print(z)
z= X % Y
print(z)
z= X ** Y
print(z)
print ("Arithmetic operations have been performed successfully")

print(X==Y)

X!=Y
X>Y
X<Y
X>=Y
X<=Y
print ("Comparison operations have been performed successfully")
print(True-5)
print(False-5)
print ("Boolean operations have been performed successfully")
print(True+True)
print(False+False)
print(True+False) 
print(10+"welocm"   )      


