name: Hello world
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: buildsteps
            run: echo "hi ${{ MYNAME }}"
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: teststeps
          run: echo " this is ${{ MYNAME }}"
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: depo
        run: echo " his is ${{ MYNAME }}"

  
