name: Hello world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: buildsteps
            run: echo "hi build"
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: teststeps
          run: echo " this is test"
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: depo
        run: echo " his is depopy"

  
